accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<pk>', views.any_user_profile, name='any_profile'),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('new/', views.NewProjectView.as_view(), name='new_project'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('applications/', views.applications_view, name='applications'),
    path('delete/<pk>/', views.DeleteProjectView.as_view(), name='delete_project'),
    path('<pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('edit/<pk>', views.EditProjectView.as_view(), name='edit_project'),
    path('position/<position_pk>/application', views.position_apply, name='apply'),
    path('applications/<application_pk>/<status>', views.application_status_view, name='app_status')
]

team_builder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Timestampable(models.Model):
    '''
        Abstract Model to give Models where it's used on extra
        Functionality.
    '''
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    @property
    def changed(self):
        return True if self.modified_at else False

    def save(self, *args, **kwargs):
        if self.pk:
            self.modified = timezone.now()
        return super(Timestampable, self).save(*args, **kwargs)


class Skill(models.Model):
    '''Model to set Skills for Users and Projects'''
    PYTHON = 'PY'
    JAVA = 'JV'
    JAVASCRIPT = 'JS'
    PHP = 'PHP'
    RUBY = 'RU'
    DESIGNER = 'DES'
    ANDROID = 'AN'
    WORDPRESS = 'WP'
    IOS = 'IOS'
    SKILL_CHOICES = (
        (PYTHON, 'Python'),
        (JAVA, 'Java'),
        (JAVASCRIPT, 'JavaScript'),
        (PHP, 'Php'),
        (RUBY, 'Ruby'),
        (DESIGNER, 'Designer'),
        (ANDROID, 'Android'),
        (WORDPRESS, 'WordPress'),
        (IOS, 'iOS'),
    )
    name = models.CharField(max_length=50,
                            choices=SKILL_CHOICES,
                            default="",
                            blank=True)

    def __str__(self):
        return self.get_name_display()


class Profile(Timestampable, models.Model):
    '''User Profile Model'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, blank=True, default='')
    last_name = models.CharField(max_length=50, blank=True, default='')
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    description = models.CharField(max_length=600, blank=True, default="")
    skills = models.ManyToManyField(Skill, blank=True)

    def __str__(self):
        return f"Profile of {self.user} PK: {self.pk}"


class SelfChoosenSkill(models.Model):
    '''Additional Skills'''
    name = models.CharField(max_length=40, blank=True)
    profile = models.ForeignKey(Profile,
                                on_delete=models.CASCADE,
                                related_name='extra_skills')

    def __str__(self):
        return self.name


class UserProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=90)
    url = models.URLField()

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.forms.widgets import Textarea, TextInput
from django.contrib.auth.models import User

from .models import Profile, Skill, SelfChoosenSkill, UserProject


class UserEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username']


class ProfileEditForm(forms.ModelForm):
    '''Form to edit your Profile'''
    skills = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Skill.objects.all()
    )

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'description',
            'image',
            'skills',
        ]
        widgets = {
            'description': Textarea(
                attrs={'placeholder': 'Enter your description here'}
            ),
            'first_name': TextInput(
                attrs={'placeholder': 'Enter your first name here'}
            ),
            'last_name': TextInput(
                attrs={'placeholder': 'Enter your last name here'}
            ),
        }


#  Inline Formset to add mulitple Skills within one form submission
SkillFormSet = forms.modelformset_factory(SelfChoosenSkill,
                                          fields=('name',),
                                          extra=1,
                                          min_num=0)

UserProjectFormSet = forms.modelformset_factory(UserProject,
                                                fields=('title', 'url',),
                                                extra=1,
                                                min_num=0)

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect

from .models import Profile, SelfChoosenSkill, UserProject
from .forms import ProfileEditForm, SkillFormSet
from projects.models import Project


@login_required
def user_profile(request):
    '''Shows the profile of the current user'''
    profile = request.user.profile
    projects = Project.objects.filter(user=request.user)
    attempted_projects = Project.objects.filter(
        positions__applications__applicant=request.user).exclude(
            positions__applications__status='P').exclude(
                positions__applications__status='R')
    user_projects = UserProject.objects.filter(user=request.user)

    context = {'object': profile,
               'projects': projects,
               'attempted_projects': attempted_projects,
               'user_projects': user_projects}

    return render(request, 'accounts/profile.html', context)


@login_required
def any_user_profile(request, pk):
    '''Shows the profile of all user except the current user'''
    profile = Profile.objects.get(id=pk)
    projects = Project.objects.filter(user=profile.user)
    attempted_projects = Project.objects.filter(
        positions__applications__applicant=profile.user).exclude(
            positions__applications__status='P').exclude(
                positions__applications__status='R')
    user_projects = UserProject.objects.filter(user=profile.user)

    context = {'object': profile,
               'projects': projects,
               'attempted_projects': attempted_projects,
               'user_projects': user_projects}

    return render(request, 'accounts/profile.html', context)


@login_required
def edit_profile(request):
    '''Used to edit User Profiles'''
    profile = request.user.profile
    if request.method == 'POST':
        profile_form = ProfileEditForm(request.POST, request.FILES,
                                       instance=profile)
        formset = SkillFormSet(request.POST,
                               queryset=SelfChoosenSkill.objects.filter(
                                   profile=profile))
        #  user_project_formset = UserProjectFormSet(request.POST,
         #                                         queryset=UserProject.objects.filter(user=request.user))

        if profile_form.is_valid():
            profile = profile_form.save()
            if formset.is_valid():
                skills = formset.save(commit=False)
                for skill in skills:
                    skill.profile = profile
                    skill.save()
                #if user_project_formset.is_valid():
                 #   print('user project valid')
                   # user_project = user_project_formset.save(commit=False)
                    #for project in user_project:
                     #   project.user = profile.user
                      #  project.save()
            messages.success(
                request,
                "You edited your profile!"
            )
            return HttpResponseRedirect(reverse('accounts:profile'))

    else:
        profile_form = ProfileEditForm(instance=request.user.profile)
        formset = SkillFormSet(queryset=SelfChoosenSkill.objects.filter(
            profile=request.user.profile))
        #  user_project_formset = UserProjectFormSet(queryset=UserProject.objects.filter(user=request.user))

    context = {
        'profile_form': profile_form,
        'formset': formset,
        'object': profile,
        #'user_project_formset': user_project_formset,
    }

    return render(request, 'accounts/profile_edit.html', context)

accounts/templates/accounts/profile.html
{% extends 'layout.html' %}
{% load course_extras %}

{% block title %}Profile of {{ object.first_name }}{% endblock %}

{% block content %}
  {% if request.user == object.user  %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>
  {% endif %}
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
    {% if request.user == object.user  %}  
    <div class="circle--fluid--cell circle--fluid--secondary">
      <a class="button icon-on-left" href="{% url 'accounts:edit_profile' %}">Edit</a>
    </div>
    {% endif %}
  </div>
  
    <div class="grid-70">
      <h1>{{ object.first_name }} {{ object.last_name }}</h1>
      <div class="circle--article--body">
        <p>{{ object.description|markdown_to_html }}</p>
      </div>

      <h2>Own Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            {% if projects %}
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
            {% else %}
            <th>No projects yet...</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for project in projects %}
          <tr class="clickable-row" data-href="{% url 'projects:project_detail' pk=project.pk %}">
            <td>
              <h3>{{ project.title }}</h3>
            </td>
            <td class="circle--cell--right">
              {% for position in project.positions.all %}
              <span class="secondary-label">{{ position.name }}</span>
              {% endfor %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <h2>Attempted Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            {% if attempted_projects %}
            <th>Project Title</th>
            {% else %}
            <th>No projects to show yet...</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for project in attempted_projects %}
          <tr class="clickable-row" data-href="{% url 'projects:project_detail' pk=project.pk %}">
            <td>
              <h3>{{ project.title }}</h3>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <div class="circle--primary--avatar">
          <img src="{{ object.image.url }}" width="100%">
        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="unloaded">
          {% for skill in object.skills.all %}
          <li>{{ skill }}</li>
          {% endfor %}
        </ul>
        <h4>More Skills</h4>
        <ul class="unloaded">
          {% if object.extra_skills.all %}
          {% for skill in object.extra_skills.all %}
          <li>{{ skill.name }}</li>
          {% endfor %}
          {% else %}
          <li>Nothing here yet...</li>
          {% endif %}
        </ul>
      </div>
      <!--
      <div class="circle--secondary--module">
        <h4>Own Projects outside of this Website:</h4>
        <ul class="circle--link--list">
          {% if user_projects %}
          {% for project in user_projects %}
          <span>Title:</span>
          <li>{{ project.title }}</li>
          <span>Url:</span>
          <li><a href="{{ project.url }}">{{ project.url }}</a></li>
          {% endfor %}
          {% else %}
          <li>Nothing to show yet...</li>
          {% endif %}
        </ul>
      </div>-->
    </div>

  </div>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'layout.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <form method="post" action="{% url 'accounts:edit_profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="bounds circle--page">
      <div class="circle--page--header circle--fluid">
        <div class="circle--fluid--cell circle--fluid--primary">
          <h2>Profile</h2>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <input type="submit" class="button button-primary icon-on-left" value="Save Changes">
        </div>
      </div>

      <div class="grid-70">
        <p>First Name:</p>
        {{ profile_form.first_name}}
        <p>Last Name:</p>
        {{ profile_form.last_name}}
        <div class="circle--article--body">
          <p>Description:</p>
          {{ profile_form.description }}
        </div>
      </div>

      <div class="grid-25 grid-push-5">

        <div class="circle--secondary--module">
          <div class="circle--primary--avatar">
            <img src="{{ object.image.url }}" width="100%">
            {{ profile_form.image }}
          </div>
        </div>

        <div class="circle--secondary--module">
          <h4>My Skills</h4>
          <ul class="circle--clone--list">
            {% for skill in profile_form.skills %}
            {{ skill }}
            {% endfor %}
            {{ formset.management_form }}
            {% for form in formset %}
            <li class="skill-formset">
              {{ form.id }}
              {{ form.name }}
            </li>
            {% endfor %}
          </ul>
        </div>
        <!--
        <div class="circle--secondary--module">
          <h4>My Projects</h4>
          <ul class="circle--clone--list">
            {{ user_project_formset.management_form }}
            {% for project in user_project_formset %}
            <li class="project-formset">
              {{ project.id }}
              <span>Title:</span>
              {{ project.title }}
              <span>Url:</span>
              {{ project.url }}
            </li>
            {% endfor %}
          </ul>
        </div>-->
      </div>

    </div>
  </form>
{% endblock %}

{% block js %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'social_app/js/jquery.formset.js' %}"></script>
    <script>
        $('.skill-formset').formset({
            addText: 'Add skill',
            deleteText: 'Remove'
        });
    </script>
    <!--
    <script>
        $('.project-formset').formset({
            addText: 'Add project',
            deleteText: 'Remove'
        });
    </script>-->
{% endblock js %}

accounts/templates/accounts/signup.html
{% extends 'social_app/layout.html' %}

{% block content %}
  <div class="bounds">
    <div class="grid-30 centered">
      <h2>Sign Up</h2>
      <form>
        <input type="email" placeholder="Email Address" />
        <input type="password" placeholder="Password" />
        <input type="password" placeholder="Confirm Password" />
        <button class="button-primary">Sign Up</button>
        <a class="button" href="signin.html">Sign In</a>
      </form>
    </div>
  </div>
{% endblock %}