accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<pk>', views.any_user_profile, name='any_profile'),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('new/', views.NewProjectView.as_view(), name='new_project'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('applications/', views.applications_view, name='applications'),
    path('delete/<pk>/', views.DeleteProjectView.as_view(), name='delete_project'),
    path('<pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('edit/<pk>', views.EditProjectView.as_view(), name='edit_project'),
    path('position/<position_pk>/application', views.position_apply, name='apply'),
    path('applications/<application_pk>/<status>', views.application_status_view, name='app_status')
]

team_builder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Timestampable(models.Model):
    ''' 
        Abstract Model to give Models where it's used on extra
        Functionality.
    '''
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    @property
    def changed(self):
        return True if self.modified_at else False

    def save(self, *args, **kwargs):
        if self.pk:
            self.modified = timezone.now()
        return super(Timestampable, self).save(*args, **kwargs)


class Project(Timestampable, models.Model):
    '''Project Model'''
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='projects')
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=600)
    duration = models.IntegerField()
    requirements = models.CharField(max_length=255)

    @property
    def available_positions(self):
        '''Model property extracting Positions which are available'''
        return self.positions.exclude(applications__status='A')

    def __str__(self):
        return self.title


class Position(models.Model):
    '''Position Model'''
    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                related_name='positions')
    name = models.CharField(max_length=100)
    skills = models.ManyToManyField('accounts.Skill', blank=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    description = models.CharField(max_length=500)
    length = models.IntegerField()

    def __str__(self):
        return self.name


class Application(Timestampable, models.Model):
    '''Model to handle User Applications for a Position'''
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('R', 'Rejected'),
    )
    applicant = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.ForeignKey(Position,
                                 on_delete=models.CASCADE,
                                 related_name='applications')
    status = models.CharField(max_length=1,
                              choices=STATUS_CHOICES,
                              default='P')

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Applicant: {self.applicant}"

projects/forms.py
from django import forms
from django.forms.widgets import Textarea, TextInput

from accounts.models import Skill
from .models import Project, Position


class ProjectEditForm(forms.ModelForm):
    '''Form to edit Projects'''
    class Meta:
        model = Project
        fields = [
            'title',
            'description',
            'duration',
            'requirements',
        ]
        widgets = {
            'title': TextInput(
                attrs={'placeholder': 'Enter a project title'}
            ),
            'description': Textarea(
                attrs={'placeholder': 'Enter a project description'}
            ),
            'requirements': Textarea(
                attrs={'placeholder': 'Enter project requirements'}
            ),
        }


class PositionEditForm(forms.ModelForm):
    '''Form to edit a Position'''
    skills = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Skill.objects.all()
    )

    class Meta:
        model = Position
        fields = [
            'name',
            'length',
            'description',
            'skills',
        ]
        widgets = {
            'name': TextInput(
                attrs={'placeholder': 'Enter a position title'}
            ),
            'description': Textarea(
                attrs={'placeholder': 'Enter a description'}
            ),
        }


#  Inline Formset to add multiple Positions in one Form
PositionFormSet = forms.modelformset_factory(Position,
                                             form=PositionEditForm,
                                             fields=('name',
                                                     'length',
                                                     'description',
                                                     'skills'),
                                             can_delete=True,
                                             min_num=1)

projects/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from braces.views import LoginRequiredMixin
from notifications.signals import notify

from .models import Project, Position, Application
from .forms import ProjectEditForm, PositionFormSet


class ProjectDetailView(LoginRequiredMixin, DetailView):
    '''View to show one Project'''
    model = Project
    template_name = 'projects/project.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['positions'] = Position.objects.filter(
            project=context['object']).exclude(applications__status='A')
        context['applied'] = Position.objects.filter(
            project=context['object'],
            applications__applicant=self.request.user)
        context['applications'] = Application.objects.filter(
            position__project=context['object'])
        return context


class NewProjectView(LoginRequiredMixin, CreateView):
    '''View to create a new Project'''
    model = Project
    form_class = ProjectEditForm
    template_name = 'projects/project_new.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = PositionFormSet(
            queryset=Position.objects.none()
        )
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = form_class(self.request.POST)
        formset = PositionFormSet(
            self.request.POST,
            queryset=Position.objects.none()
        )

        if form.is_valid():
            project = form.save(commit=False)
            project.user = self.request.user
            project.save()
            if formset.is_valid():
                positions = formset.save(commit=False)
                for position in positions:
                    position.project = project
                    position.user = self.request.user
                    position.save()
                formset.save_m2m()
                messages.success(
                    request,
                    "You successfully created a new Project!"
                    )
        return HttpResponseRedirect(reverse('home'))


class EditProjectView(LoginRequiredMixin, UpdateView):
    '''View to edit a Project'''
    model = Project
    form_class = ProjectEditForm
    template_name = 'projects/project_edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = PositionFormSet(
            queryset=Position.objects.filter(project=self.get_object())
        )
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = form_class(self.request.POST, instance=self.get_object())
        formset = PositionFormSet(
            self.request.POST,
            queryset=Position.objects.filter(project=self.get_object())
        )

        if form.is_valid():
            project = form.save(commit=False)
            project.user = self.request.user
            project.save()
            if formset.is_valid():
                positions = formset.save(commit=False)
                for position in positions:
                    position.project = project
                    position.user = self.request.user
                    position.save()
                formset.save_m2m()
                messages.success(
                    request,
                    "You successfully edited your Project!"
                    )
        return HttpResponseRedirect(reverse('projects:project_detail',
                                    kwargs={"pk": project.pk}))


class DeleteProjectView(LoginRequiredMixin, DeleteView):
    '''View to delete a Project'''
    model = Project
    success_url = reverse_lazy('home')


@login_required
def position_apply(request, position_pk):
    '''View to apply for a position and send Notifications'''

    position = Position.objects.get(id=position_pk)
    project = position.project
    application = Application.objects.filter(applicant=request.user,
                                             position=position)

    if application.exists():
        return HttpResponseRedirect(reverse('projects:project_detail',
                                    kwargs={"pk": project.pk}))

    Application.objects.create(applicant=request.user, position=position)

    notify.send(
        request.user,
        recipient=request.user,
        verb=f"You applied to {position.name} for the project {project.title}"
    )

    notify.send(
        request.user,
        recipient=project.user,
        verb=f"{request.user} applied to the Positon:"
             f" {position.name} for Project: {project.title}"
    )

    return HttpResponseRedirect(reverse('home'))


@login_required
def notifications_view(request):
    '''View to provide and render Notifications'''
    unread_notifs = request.user.notifications.unread()
    return render(request,
                  'projects/notifications.html',
                  {'unread_notifs': unread_notifs})


@login_required
def applications_view(request):
    '''View to render, show and filter Applications for a Project'''
    applications = Application.objects.filter(
        position__project__user=request.user)
    projects = Project.objects.filter(user=request.user)
    positions = Position.objects.filter(
        user=request.user).values('name').distinct()

    status_filter = request.GET.get('status_filter')
    if status_filter:
        applications = Application.objects.filter(
            Q(position__project__user=request.user) &
            Q(status=status_filter))

    project_filter = request.GET.get('project_filter')
    if project_filter:
        applications = Application.objects.filter(
            position__project__pk=project_filter)

    position_filter = request.GET.get('position_filter')
    if position_filter:
        applications = Application.objects.filter(
            position__project__positions__name=position_filter)

    return render(request,
                  'projects/applications.html', {'applications': applications,
                                                 'projects': projects,
                                                 'positions': positions})


@login_required
def application_status_view(request, application_pk, status):
    '''View to change Application status and send notifications'''
    application = Application.objects.get(id=application_pk)
    #  position = Position.objects.get(applications__id=application.id)

    if status == "accepted":
        application.status = "A"
        application.save()

        notify.send(
            request.user,
            recipient=application.applicant,
            verb=f"You are accepted for the Position: {application.position} "
                 f"of Project: {application.position.project}"
        )
        notify.send(
            request.user,
            recipient=request.user,
            verb=f"You accepted {application.applicant} "
                 f"for the Position: {application.position}"
        )

    if status == "rejected":
        application.status = "R"
        application.save()

        notify.send(
            request.user,
            recipient=application.applicant,
            verb=f"You got rejected for the Position: {application.position} "
                 f"of Project: {application.position.project}"
        )
        notify.send(
            request.user,
            recipient=request.user,
            verb=f"You rejected {application.applicant} "
                 f"for the Position: {application.position}"
        )

    return HttpResponseRedirect(reverse('projects:applications'))

projects/templates/projects/applications.html
{% extends 'layout.html' %}

{% block title %}Applications{% endblock %}

{% block content %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-20">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a href="{% url 'projects:applications' %}">All Applications</a></li>
          <li><a href="?status_filter=P">New Applications</a></li>
          <li><a href="?status_filter=A">Accepted</a></li>
          <li><a href="?status_filter=R">Rejected</a></li>
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
          <li><a href="{% url 'projects:applications' %}">All Projects</a></li>
          {% for project in projects %}
          <li><a href="?project_filter={{ project.id }}">{{ project.title }}</a></li>
          {% endfor %}
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
          <li><a href="{% url 'projects:applications' %}">All Needs</a></li>
          {% for position in positions %}
          <li><a href="?position_filter={{ position.name }}">{{ position.name }}</a></li>
          {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-80 grid-push-5">
      {% if applications %}
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for application in applications %}
          <tr class="clickable-row" data-href="{% url 'accounts:any_profile' pk=application.applicant.profile.id %}">
            <td>
              <h3>{{ application.applicant }}</h3>
              <p>{{ application.position.project.title }}</p>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ application.position.name }}</span>
            </td>
            <td>
              {% if application.status == 'P' %}
              <a class="button button-primary" href="{% url 'projects:app_status' application_pk=application.pk status='accepted' %}">Accept</a>
              <a class="button button-secondary" href="{% url 'projects:app_status' application_pk=application.pk status='rejected' %}">Reject</a>
              {% elif application.status == 'A' %}
              <p>You accepted {{ application.applicant }}</p>
              {% elif application.status == 'R' %}
              <p>You rejected {{ application.applicant }}</p>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
    <p>No applications yet...</p>
    {% endif %}
    </div>

  </div>
{% endblock %}

projects/templates/projects/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Projects</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="{% url 'projects:new_project' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list already-set">
          <li><a href="{% url 'home' %}">All Needs</a></li>
          {% for position in positions %}
          <li><a href="?position={{ position.name }}">{{ position.name }}</a></li>
          {% endfor %}
        </ul>
        <a href="?skill=userskill">Match my Skillset</a>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          {% for project in projects %}
          <tr class="clickable-row" data-href="{% url 'projects:project_detail' pk=project.pk %}">
            <td>
              <h3>{{ project.title }}</h3>
            </td>
            <td class="circle--cell--right">
              {% if project.available_positions %}
              <span class="secondary-label">{{ project.available_positions|join:", " }}</span>
              {% else %}
              <p>No open positions...</p>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% else %}
  <h2 class="newuser">Please login or signup to use the features of this site</h2>
  {% endif %}
{% endblock %}

projects/templates/projects/notifications.html
{% extends "layout.html" %}

{% block title %}Notifications{% endblock %}

{% block content %}

<div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
          <h2>Recent Notifications</h2>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">

    <div class="grid-70">

      <div class="circle--article--body">
      {% if unread_notifs %}
        {% for message in unread_notifs %}
            <p>{{ message.verb }}</p>
            <p><strong>{{ message.timestamp}}</strong></p>
            <hr/>
          {% endfor %}
      {% else %}
          <p>No messages to display.</p>
      {% endif %}
      </div>
    </div>

  </div>
{% endblock %}

projects/templates/projects/project.html
{% extends 'layout.html' %}
{% load course_extras %}

{% block title %}Project | {{ object.title }}{% endblock %}

{% block content %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        {% if request.user == object.user %}
          <a class="button" href="{% url 'projects:edit_project' pk=object.pk %}">Edit Project</a>
          <a class="button button-text" href="{% url 'projects:delete_project' pk=object.pk %}">Delete Project</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ object.title }}</h1>
        <p class="circle--article--byline">Project Owner: <a href="{% url 'accounts:any_profile' pk=object.user.profile.id %}">{{ object.user }}</a></p>
      </div>

      <div class="circle--article--body">
        <p>{{ object.description|markdown_to_html }}</p>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>
        <ul class="circle--group--list">
          {% if not positions %}
          <li>There are no open positions right now...</li>
          {% else %}
          {% for position in positions %}
          <li>
            <h3>{{ position.name }}</h3>
            {% if position.length %}
            <span>Length of involvement: {{ position.length}} hours/week</span>
            {% endif %}
            <p>{{  position.description|markdown_to_html }}</p>
            <h3>Desired Skill:</h3>
            <tbody>
              <td class="circle--cell">
                {% for skill in position.skills.all %}
                <span>{{ skill|join:", " }}</span>
                {% endfor %}
              </td>
            </tbody><br>
            {% if request.user != object.user %}
              {% if position in applied %}
                <button disabled class="button button-inactive">Already Applied</button>
              {% else %}
              <a class="button button-primary" href="{% url 'projects:apply' position_pk=position.id %}">Apply</a>
              {% endif %}
            {% endif %}
          </li>
          {% endfor %}
          {% endif %}
        {% if request.user == object.user %}
        <h2>All Applications for this Project</h2>
        {% if applications %}
        <table class="u-full-width circle--table">
          <thead>
            <tr>
              <th>Applicant</th>
              <th class="circle--cell--right">Applicant Position</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for application in applications %}
            <tr class="clickable-row" data-href="{% url 'accounts:any_profile' pk=application.applicant.profile.id %}">
              <td>
                <h3>{{ application.applicant }}</h3>
                <p>{{ application.position.project.title }}</p>
              </td>
              <td class="circle--cell--right">
                <span class="secondary-label">{{ application.position.name }}</span>
              </td>
              <td>
                {% if application.status == 'P' %}
                <a class="button button-primary" href="{% url 'projects:app_status' application_pk=application.pk status='accepted' %}">Accept</a>
                <a class="button button-secondary" href="{% url 'projects:app_status' application_pk=application.pk status='rejected' %}">Reject</a>
                {% elif application.status == 'A' %}
                <p>You accepted {{ application.applicant }}</p>
                {% elif application.status == 'R' %}
                <p>You rejected {{ application.applicant }}</p>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
      <p>No applications yet...</p>
      {% endif %}
      {% endif %}
      </div>
    </div>

    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <h3>Project Needs</h3>
        <ul class="circle--link--list">
          {% for position in object.positions.all %}
          <li><a>{{ position.name }}</a></li>
          {% endfor %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ object.duration }} hours</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <p>{{ object.requirements }}</p>
      </div>

    </div>
  </div>
{% endblock %}

projects/templates/projects/project_confirm_delete.html
{% extends 'layout.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<form class="grid-45 centered" method="post">
    {% csrf_token %}
    <h2 class="grid-45 centered">Attention!</h2>
    <p>Are you sure you want to delete "{{ object.title }}"?</p>
    <button type="submit" class="button button-primary">Yes</button>
    <a class="button button-secondary" href="{% url 'projects:project_detail' pk=object.pk %}">No</a>
</form>
{% endblock %}

projects/templates/projects/project_edit.html
{% extends 'layout.html' %}

{% block title %}Edit Project{% endblock %}

{% block content %}
  <form action="{% url 'projects:edit_project' pk=object.pk %}" method="POST">
    {% csrf_token %}
    <div class="circle--actions--bar">
      <div class="bounds">
        <div class="grid-100">
          <a class="button button-text" href="index.html">Discard</a>
          <button type="submit" class="button button-primary icon-on-left">Save Project</button>
        </div>
      </div>
    </div>
    
    <div class="bounds circle--page circle--article">
      <div class="grid-70">
        <div class="circle--article--body">
          <h2>Project Title</h2>
          {{ form.title.errors }}
          {{ form.title }}
          <h2>Description</h2>
          {{ form.description.errors }}
          {{ form.description }}
        </div>

        <div class="circle--project--positions">
          <h2>Positions</h2>

          <ul class="circle--group--list circle--clone--list">
            {{ formset.management_form }}
            {% for form in formset %}
            <li class="formset">
              {{ form.id }}
              <span>Position Name:</span>
              {{ form.name }}
              <span>Lenght of involvement hours/week:</span>
              {{ form.length }}
              <span>Position Description:</span>
              {{ form.description }}
              <span>Needed Skills:</span>
              {% for skill in form.skills %}
                {{ skill }}
              {% endfor %}
            </li>
            {% endfor %}
          </ul>
          <button type="submit" class="button button-primary icon-on-left">Save Project</button>

        </div>
      </div>

      <div class="grid-25 grid-push-5">

        <div class="circle--secondary--module">
          <h3>Project Timeline</h3>
          {{ form.duration.errors }}
          {{ form.duration }}
        </div>

        <div class="circle--secondary--module">
          <h3>Applicant Requirements</h3>
          {{ form.requirements.errors }}
          {{ form.requirements }}
        </div>

      </div>
    </div>
  </form>
{% endblock %}

{% block js %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'social_app/js/jquery.formset.js' %}"></script>
    <script>
        $('.formset').formset({
            addText: 'Add position',
            deleteText: 'Remove'
        });
    </script>
{% endblock js %}

projects/templates/projects/project_new.html
{% extends 'layout.html' %}

{% block title %}New Project{% endblock %}

{% block content %}
  <form action="{% url 'projects:new_project' %}" method="POST">
    {% csrf_token %}
    <div class="circle--actions--bar">
      <div class="bounds">
        <div class="grid-100">
          <a class="button button-text" href="index.html">Discard</a>
          <button type="submit" class="button button-primary icon-on-left">Save Project</button>
        </div>
      </div>
    </div>
    
    <div class="bounds circle--page circle--article">
      <div class="grid-70">
        <div class="circle--article--body">
          <h2>Project Title</h2>
          {{ form.title.errors }}
          {{ form.title }}
          <h2>Description</h2>
          {{ form.description.errors }}
          {{ form.description }}
        </div>

        <div class="circle--project--positions">
          <h2>Positions</h2>

          <ul class="circle--group--list circle--clone--list">
            {{ formset.management_form }}
            {% for form in formset %}
            <li class="formset">
              {{ form.id }}
              <span>Position Name:</span>
              {{ form.name }}
              <span>Lenght of involvement hours/week:</span>
              {{ form.length }}
              <span>Position Description:</span>
              {{ form.description }}
              <span>Needed Skills:</span>
              {% for skill in form.skills %}
                {{ skill }}
              {% endfor %}
            </li>
            {% endfor %}
          </ul>
          <button type="submit" class="button button-primary icon-on-left">Save Project</button>

        </div>
      </div>

      <div class="grid-25 grid-push-5">

        <div class="circle--secondary--module">
          <h3>Project Timeline</h3>
          {{ form.duration }}
        </div>

        <div class="circle--secondary--module">
          <h3>Applicant Requirements</h3>
          {{ form.requirements }}
        </div>

      </div>
    </div>
  </form>
{% endblock %}

{% block js %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'social_app/js/jquery.formset.js' %}"></script>
    <script>
        $('.formset').formset({
            addText: 'Add position',
            deleteText: 'Remove'
        });
    </script>
{% endblock js %}