accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<pk>', views.any_user_profile, name='any_profile'),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('new/', views.NewProjectView.as_view(), name='new_project'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('applications/', views.applications_view, name='applications'),
    path('delete/<pk>/', views.DeleteProjectView.as_view(), name='delete_project'),
    path('<pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('edit/<pk>', views.EditProjectView.as_view(), name='edit_project'),
    path('position/<position_pk>/application', views.position_apply, name='apply'),
    path('applications/<application_pk>/<status>', views.application_status_view, name='app_status')
]

team_builder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/layout.html
{% load static from static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Projectify | {% block title %}{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'social_app/css/global.css' %}">

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static 'social_app/js/autogrow.js' %}"></script>
  <script type="text/javascript" src="{% static 'social_app/js/global.js' %}"></script>


</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <form method="GET">
              <input type="text" name="search_box" placeholder="Search Projects..." />
              <button>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
              </button>
            </form>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              {% if user.is_authenticated %}
              <li><a href="{% url 'projects:notifications' %}">Notifications</a></li>
              <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
              <li><a href="{% url 'account_logout' %}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
              <li><a href="{% url 'account_login' %}">Login</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
      {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }} messages"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
      {% endif %}
    </div>
  </header>
  {% block content %}{% endblock %}
  {% block js %}{% endblock %}
</body>
</html>